title: "Foremast - The Application Manager for Kubernetes"
url: https://foremast.io # site url
## BaseURL - change based on repository from where this is going to be hosted
baseurl: "/foremast"

repo: http://github.com/intuit/foremast
comments: false

plugins:
  - jekyll-last-modified-at
  - jekyll-sitemap
  - jemoji

collections:

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : rouge

source: ./
destination: ./_site

# Author settings
author:
  name     : "The Foremast Team"

# social settings
og_locale: "en_US"

kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids:       true
  toc_levels:     1..3

exclude: ["vendor", "Gemfile", "Gemfile.lock", "README.md", "LICENSE.txt", "Rakefile"]
